#!/bin/sh

echo I am building2...
echo Changing2 1
echo Changing2 2
echo I am building2...
echo I am building2...
echo I am building2...
echo I am building2...
echo I am building2...
echo I am building2...
